-- 001_sample_documents.sql
-- Inserts sample document metadata only. Versions, chunks, and logs are intentionally left empty.

INSERT INTO documents (
    internal_code,
    title,
    document_type,
    data_type,
    short_summary,
    keywords,
    main_topics,
    system_category,
    responsible_unit,
    source_system,
    source_record_id,
    source_url,
    storage_path,
    original_file_name,
    file_type,
    language,
    status
) VALUES
(
    'LEGAL-CATHAYBOX-001',
    'CathayBox legal opinion',
    'legal_opinion',
    'legal_analysis',
    'Legal opinion covering internal use of CathayBox for file sharing, access control, and handling of confidential business information.',
    ARRAY['CathayBox', 'legal opinion', 'file sharing', 'access control', 'confidential information'],
    ARRAY['cloud storage governance', 'personal data protection', 'internal collaboration'],
    'Legal and Compliance',
    'Legal Department',
    'legal_knowledge_base',
    'LKB-2025-0001',
    'https://intranet.example.com/legal/opinions/cathaybox-legal-opinion',
    's3://audit-ai-db/raw/legal/LEGAL-CATHAYBOX-001.pdf',
    'CathayBox_legal_opinion.pdf',
    'pdf',
    'en',
    'active'
),
(
    'POLICY-AI-SERVICE-001',
    '人工智慧(AI)服務應用管理要點',
    'policy_guideline',
    'internal_policy',
    '管理人工智慧服務導入、使用、風險評估、資料保護及權責分工之內部作業要點。',
    ARRAY['人工智慧', 'AI服務', '風險評估', '資料保護', '內部管理'],
    ARRAY['AI governance', 'service approval', 'risk control', 'data protection'],
    'AI Governance',
    'Digital Transformation Office',
    'policy_portal',
    'POL-2025-AI-001',
    'https://intranet.example.com/policies/ai-service-management-guidelines',
    's3://audit-ai-db/raw/policies/POLICY-AI-SERVICE-001.docx',
    '人工智慧(AI)服務應用管理要點.docx',
    'docx',
    'zh-TW',
    'active'
),
(
    'MANUAL-R-ANALYTICS-001',
    'R語言資料分析平台使用說明',
    'user_manual',
    'technical_manual',
    'R語言資料分析平台之帳號申請、資料上傳、分析環境、套件管理及使用注意事項說明。',
    ARRAY['R語言', '資料分析', '平台使用', '套件管理', '帳號申請'],
    ARRAY['analytics platform', 'user access', 'data upload', 'package management'],
    'Data Analytics Platform',
    'Data Analytics Team',
    'internal_wiki',
    'WIKI-R-ANALYTICS-001',
    'https://intranet.example.com/wiki/r-analytics-platform-user-guide',
    's3://audit-ai-db/raw/manuals/MANUAL-R-ANALYTICS-001.pdf',
    'R語言資料分析平台使用說明.pdf',
    'pdf',
    'zh-TW',
    'active'
)
ON CONFLICT (internal_code) DO UPDATE SET
    title = EXCLUDED.title,
    document_type = EXCLUDED.document_type,
    data_type = EXCLUDED.data_type,
    short_summary = EXCLUDED.short_summary,
    keywords = EXCLUDED.keywords,
    main_topics = EXCLUDED.main_topics,
    system_category = EXCLUDED.system_category,
    responsible_unit = EXCLUDED.responsible_unit,
    source_system = EXCLUDED.source_system,
    source_record_id = EXCLUDED.source_record_id,
    source_url = EXCLUDED.source_url,
    storage_path = EXCLUDED.storage_path,
    original_file_name = EXCLUDED.original_file_name,
    file_type = EXCLUDED.file_type,
    language = EXCLUDED.language,
    status = EXCLUDED.status,
    updated_at = CURRENT_TIMESTAMP;

